steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/founderbot/unova-management-dashboard:latest'
      - '.'

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/founderbot/unova-management-dashboard:latest'

options:
  logging: CLOUD_LOGGING_ONLY
